services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/configs
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app_network

volumes:
  caddy_data:
  caddy_config:

networks:
  app_network:
    driver: bridge