services:
  portainer:
    image: portainer/portainer-ce:alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data 
    networks:
      - caddy_app_network

volumes:
  data:

networks:
  caddy_app_network:
    external: true