services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=9090
      - TORRENTING_PORT=42473
    volumes:
      - /mnt/nas/qbittorrent/config:/config
      - /mnt/share/downloads:/downloads #optional
      - /mnt/share/media:/media #optional
    ports:
      - 9090:9090
      - 42473:42473
      - 42473:42473/udp
    restart: unless-stopped
    network_mode: bridge
