services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/heimdall/config:/config
    restart: unless-stopped
    networks:
      - gateway_default

networks:
  gateway_default:
    external: true